### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by afridiwaqar** [MusheAbdulHakim/TailorShop-Management-System#1]
Hello there

I download your project and tried to run but getting error with missing file "addmeasurement.php" and "editmeasurement.php". could you kindly look into it?

**Comment by MusheAbdulHakim** [comment]
make sure you clone from the main branch.It is the most up to date.Plus some of the pages are not build yet.I am doing this at my free period.

**Comment by MusheAbdulHakim** [comment]
but i will look into the page that is missing and either build the page or unlink them.

**Comment by MusheAbdulHakim** [comment]
the issue has been solved since i have decided to rewrite the codebase with the laravel framework.
Everything is now working fine.
